# Generated by Django 5.1.3 on 2024-11-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=100)),
                ('bride_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateTimeField()),
                ('organizers', models.TextField()),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.TextField()),
                ('venue_geolocation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
