# Generated by Django 5.1.3 on 2024-11-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='venue_geolocation',
        ),
        migrations.AddField(
            model_name='invitation',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.template'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='venue_location',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='bride_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='groom_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='organizers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='venue_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('animated', 'Animated')], max_length=10),
        ),
    ]
