# Generated by Django 5.1.3 on 2024-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_faq_remove_invitation_venue_geolocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
