# Generated by Django 5.1.1 on 2024-11-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_templatetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='image',
        ),
        migrations.AddField(
            model_name='template',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='template',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='template',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='template',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='template',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
